## モジュールの使用方法


**モジュールの使用方法**\
import モジュール名\
モジュール名.関数名(引数)

```Python
import math
math.sqrt(10)
math.sin(100)
```

**読み込む際に別名をつける**\
import モジュール名 as 別名

```Python
import math as mm
mm.sqrt(10)
mm.sin(100)
```

## mathモジュール

In [2]:
import math


In [3]:
# 10の平方根
math.sqrt(10)

3.1622776601683795

In [4]:
# sin関数を実行
math.sin(100)

-0.5063656411097588

In [6]:
# 使用できる関数を調べる
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

### 別名で読み込み

In [7]:
import math as mm

In [8]:
mm.sqrt(10)

3.1622776601683795

## randomモジュール

In [9]:
import random

In [11]:
# 1 ~ 100の中でランダムに整数を変える
random.randint(1, 100)

21

In [19]:
# 引数のリストの中で、ランダムに値を変えす
random.choice(["雨", "晴れ", "曇り"])

'晴れ'

## ライブラリの新規インストール

- pip: Pythonライブラリを管理してくれるツール、コマンド

自分はuvを使っているので「**uv**」と「**pip install**」は混ぜるな危険\
`uv add [パッケージ]`を使って対応する
- uv: `uv add [パッケージ]`

### インストールされているパッケージリストを表示する

In [22]:
! uv pip list

Package                   Version
------------------------- -----------
anyio                     4.11.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.2
bleach                    6.3.0
certifi                   2025.10.5
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.1.0
ipython                   9.7.0
ipython-pygments-lexers   1.1.1
isoduration        

Using Python 3.12.6 environment at: c:\Users\1106024\OneDrive - 三菱倉庫\デスクトップ\0040_開発\Lab\learning\.venv


### 新規インストール

In [ ]:
! uv add japanize-matplotlib

In [25]:
! uv pip list

Package                   Version
------------------------- -----------
anyio                     4.11.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.2
bleach                    6.3.0
certifi                   2025.10.5
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.60.1
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel        

Using Python 3.12.6 environment at: c:\Users\1106024\OneDrive - 三菱倉庫\デスクトップ\0040_開発\Lab\learning\.venv


## 便利なライブラリの紹介

- numpy
- pandas
- seaborn
- plotly

In [26]:
import numpy as np

In [27]:
# 一次元配列の作り方
# listと近い
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [30]:
# 二次元配列の作り方
# 今回は2行4列の配列を定義
arr2 = np.array([[1, 2, 3, 4], [3, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [3, 6, 7, 8]])

In [31]:
# .T で転置
arr2.T

array([[1, 3],
       [2, 6],
       [3, 7],
       [4, 8]])

In [35]:
# 要素のアクセスは、インデックスを指定
arr2[1][1]

np.int64(6)

In [13]:
# クロスプラットフォーム開発を想定
from pathlib import Path

In [1]:
import pandas as pd

In [29]:
# クロスプラットフォーム開発を意識してpathlibを使用してパスを指定する
csv_path = Path("input/#4") / "california_housing_train.csv"
df = pd.read_csv(csv_path)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [30]:
df.shape

(17000, 9)

In [31]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [32]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...  
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

In [33]:
df.iloc[2:]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
5        -114.58     33.63                29.0       1387.0           236.0   
6        -114.58     33.61                25.0       2907.0           680.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
5           671.0       239.0         3.3438             74000.0  
6          1841.0       633.0         2.6768             82400.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[16998 rows x 9 columns]

In [34]:
df.iloc[2:5, 1:4]

latitude  housing_median_age  total_rooms
2     33.69                17.0        720.0
3     33.64                14.0       1501.0
4     33.57                20.0       1454.0

In [35]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [36]:
df['latitude'].mean()

np.float64(35.62522470588235)

In [37]:
df['latitude'].sum()

np.float64(605628.82)

In [38]:
df2 = df.iloc[2:, ]
df2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
5        -114.58     33.63                29.0       1387.0           236.0   
6        -114.58     33.61                25.0       2907.0           680.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
5           671.0       239.0         3.3438             74000.0  
6          1841.0       633.0         2.6768             82400.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[16998 rows x 9 columns]

In [39]:
output_path = Path("output/#4") / "filename.csv"

# 親ディレクトリ（output）が存在しない場合は作成
# parents=True: 親ディレクトリも必要に応じて作成
# exist_ok=True: 既に存在していてもエラーにしない
output_path.parent.mkdir(parents=True, exist_ok=True)

df2.to_csv(output_path)